[project]
name = "rl_intro"
version = "0.1.0"
description = "Introduction to Reinforcement Learning"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.0",
    "pytest>=8.4.0",
]

[tool.setuptools.packages.find]
where = ["rl_intro"]
